# Generated by Django 5.2.7 on 2025-11-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='company_rank',
            field=models.CharField(blank=True, choices=[('director', 'Director'), ('vice_director', 'Vice Director'), ('business_teacher', 'Business Teacher'), ('manager', 'Manager'), ('doctor', 'Doctor'), ('it_officer', 'IT Officer'), ('supervisor', 'Supervisor'), ('reception', 'Reception'), ('accountant', 'Accountant'), ('pharmacist', 'Pharmacist'), ('video grapher', 'Video Grapher')], max_length=50, null=True),
        ),
    ]
