# Generated by Django 5.2.7 on 2025-12-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0004_alter_userdetail_company_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientform',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Fema----------------le')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patientform',
            name='membership_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
