# Generated by Django 5.2.7 on 2025-12-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0005_alter_patientform_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientform',
            name='membership_no',
            field=models.CharField(max_length=50),
        ),
    ]
