# Generated by Django 5.2.7 on 2025-12-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0006_alter_patientform_membership_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientform',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
