# Generated by Django 5.2.7 on 2025-12-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0007_alter_patientform_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientform',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Fema----------------le')], max_length=1),
        ),
    ]
