# Generated by Django 5.2.7 on 2025-12-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0009_alter_patientform_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('office_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=1)),
                ('dob', models.DateField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('diabetics', models.TextField(blank=True)),
                ('hypertension', models.TextField(blank=True)),
                ('respiratory_system', models.TextField(blank=True)),
                ('digestive_system', models.TextField(blank=True)),
                ('liver_system', models.TextField(blank=True)),
                ('renal_urinary', models.TextField(blank=True)),
                ('skeletal_system', models.TextField(blank=True)),
                ('skin_disorders', models.TextField(blank=True)),
                ('cerebral_system', models.TextField(blank=True)),
                ('male_reproductive', models.TextField(blank=True)),
                ('female_reproductive', models.TextField(blank=True)),
                ('ent_system', models.TextField(blank=True)),
                ('avoid_reduce', models.TextField(blank=True)),
                ('eat_most', models.TextField(blank=True)),
                ('doctor_signature', models.TextField(blank=True)),
                ('charges', models.CharField(default='30,000/=', max_length=50)),
                ('products', models.ManyToManyField(blank=True, to='RoseNutritionLifeApp.medicine_salesform')),
            ],
        ),
    ]
