# Generated by Django 5.2.7 on 2025-12-02 09:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0010_medical'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientform',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
