# Generated by Django 5.2.7 on 2025-12-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0011_patientform_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientform',
            name='date',
        ),
        migrations.AddField(
            model_name='patientform',
            name='birth',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
