# Generated by Django 5.2.7 on 2025-12-02 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0012_remove_patientform_date_patientform_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientform',
            name='birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
