# Generated by Django 5.2.7 on 2025-12-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0013_alter_patientform_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientform',
            name='birth',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
