# Generated by Django 5.2.7 on 2025-12-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0014_alter_patientform_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine_salesform',
            name='medicine',
        ),
    ]
