# Generated by Django 5.2.7 on 2025-12-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0015_remove_medicine_salesform_medicine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical',
            old_name='cerebral_system',
            new_name='doctor_summary',
        ),
        migrations.RemoveField(
            model_name='medical',
            name='diabetics',
        ),
        migrations.RemoveField(
            model_name='medical',
            name='digestive_system',
        ),
        migrations.RemoveField(
            model_name='medical',
            name='ent_system',
        ),
        migrations.RemoveField(
            model_name='medical',
            name='female_reproductive',
        ),
        migrations.RemoveField(
            model_name='medical',
            name='hypertension',
        ),
        migrations.RemoveField(
            model_name='medical',
            name='liver_system',
        ),
        migrations.RemoveField(
            model_name='medical',
            name='male_reproductive',
        ),
        migrations.RemoveField(
            model_name='medical',
            name='renal_urinary',
        ),
        migrations.RemoveField(
            model_name='medical',
            name='respiratory_system',
        ),
        migrations.RemoveField(
            model_name='medical',
            name='skeletal_system',
        ),
        migrations.RemoveField(
            model_name='medical',
            name='skin_disorders',
        ),
    ]
