# Generated by Django 5.2.7 on 2025-12-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0016_rename_cerebral_system_medical_doctor_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='dob',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
