# Generated by Django 5.2.7 on 2025-12-04 07:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0017_alter_medical_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical',
            name='products',
        ),
        migrations.AddField(
            model_name='medical',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='medical',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='MedicineProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_no', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_no', models.CharField(blank=True, max_length=50, null=True)),
                ('medicine_name', models.CharField(max_length=200)),
                ('medicine_pv', models.PositiveIntegerField()),
                ('medicine_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confirm_payment', models.BooleanField(default=False)),
                ('medical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_products', to='RoseNutritionLifeApp.medical')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoseNutritionLifeApp.medicine_salesform')),
            ],
        ),
    ]
