# Generated by Django 5.2.7 on 2025-12-04 07:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0018_remove_medical_products_medical_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='about',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medicineproduct',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='medicineproduct',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
