# Generated by Django 5.2.7 on 2025-12-04 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0019_about_date_created_about_date_modified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_no', models.CharField(max_length=50)),
                ('member_name', models.CharField(max_length=255)),
                ('total_pv', models.PositiveIntegerField()),
                ('money', models.DecimalField(decimal_places=2, max_digits=12)),
                ('month', models.CharField(max_length=20)),
                ('status', models.CharField(default='paid', max_length=20)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_id', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
