# Generated by Django 5.2.7 on 2025-12-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0021_paymentproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproduct',
            name='membership_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentproduct',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
