# Generated by Django 5.2.7 on 2025-12-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0022_paymentproduct_membership_no_paymentproduct_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentproduct',
            name='membership_no',
        ),
        migrations.RemoveField(
            model_name='paymentproduct',
            name='month',
        ),
    ]
