# Generated by Django 5.2.7 on 2025-12-10 13:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0023_remove_paymentproduct_membership_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('medical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='RoseNutritionLifeApp.medical')),
            ],
        ),
    ]
