# Generated by Django 5.2.7 on 2025-12-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0024_medicalmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberpayment',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='memberpayment',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='paymentproduct',
            name='patient_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentproduct',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
