# Generated by Django 5.2.7 on 2025-12-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0025_remove_memberpayment_patient_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine_salesform',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicine_salesform',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicineproduct',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicineproduct',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='medicineproduct',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
