# Generated by Django 5.2.7 on 2025-12-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0026_medicine_salesform_code_medicine_salesform_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineproduct',
            name='medicine_totalcost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
