# Generated by Django 5.2.7 on 2025-12-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0027_medicineproduct_medicine_totalcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineproduct',
            name='medicine_totalcost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
