# Generated by Django 5.2.7 on 2025-12-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0028_alter_medicineproduct_medicine_totalcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineproduct',
            name='qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
