# Generated by Django 5.2.7 on 2025-12-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0029_alter_medicineproduct_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproduct',
            name='qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
