# Generated by Django 5.2.7 on 2025-12-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0034_alter_about_company_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
