# Generated by Django 5.2.7 on 2026-01-08 10:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0035_alter_userdetail_age_alter_userdetail_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineAddProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_no', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_no', models.CharField(blank=True, max_length=50, null=True)),
                ('medicine_name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('medicine_pv', models.PositiveIntegerField()),
                ('medicine_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.PositiveIntegerField()),
                ('medicine_totalcost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('confirm_payment', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoseNutritionLifeApp.medicine_salesform')),
            ],
        ),
    ]
