# Generated by Django 5.2.7 on 2026-01-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0036_medicineaddproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineaddproduct',
            name='patient_no',
        ),
        migrations.AddField(
            model_name='medicineaddproduct',
            name='member_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='medicineaddproduct',
            name='patient_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medicineaddproduct',
            name='patient_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
