# Generated by Django 5.2.7 on 2026-01-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0037_remove_medicineaddproduct_patient_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineaddproduct',
            name='confirm_payment',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
