# Generated by Django 5.2.7 on 2026-01-13 10:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0038_alter_medicineaddproduct_confirm_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(blank=True, max_length=150, null=True)),
                ('membership_no', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=150, null=True)),
                ('patient_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicineaddproduct',
            name='member_name',
        ),
        migrations.RemoveField(
            model_name='medicineaddproduct',
            name='membership_no',
        ),
        migrations.RemoveField(
            model_name='medicineaddproduct',
            name='patient_mobile',
        ),
        migrations.RemoveField(
            model_name='medicineaddproduct',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='medicineaddproduct',
            name='medicine_add',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RoseNutritionLifeApp.medicineadd'),
        ),
    ]
