# Generated by Django 5.2.7 on 2026-02-16 06:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0039_medicineadd_remove_medicineaddproduct_member_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientform',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
