# Generated by Django 5.2.7 on 2026-02-16 07:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0040_alter_patientform_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
