# Generated by Django 5.2.7 on 2026-03-10 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0043_stockadd_stock_stockaddproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('stock_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='RoseNutritionLifeApp.stockadd')),
            ],
        ),
    ]
