# Generated by Django 5.2.7 on 2026-03-10 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseNutritionLifeApp', '0044_stockpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockaddproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RoseNutritionLifeApp.stock'),
        ),
    ]
